app/controllers/BaseController.php, app/controllers/DocsController.php
And do not show empty pages if article does not exist
=> Improved getting current version and small code cleanup

app/config/highlight.php, app/config/routes.php, app/providers/Assets/ServiceProvider.php, app/providers/Routing/ServiceProvider.php
**Before**
**After**
Cc: @niden
=> Added highlight support for all languages

app/views/include/nav.volt, app/views/templates/base.volt, public/css/docs.css
Makes header no longer fixed and transitions sidebar to sticky
=> Header was fixed and this makes left sidebar sticky instead.

app/library/ClassLink.php, app/tasks/MainTask.php, app/tasks/RegenerateApiTask.php
Re-implements API regeneration from old docs repo.
To setup
`ln -s /<path_to_cphalcon>/cphalcon/ storage/repo`
Then run
`./phalcon -regenerate-api`
=> Re-implement api-regeneration

public/css/docs.css
This improve reading
Just only add 15px of bottom margin at children of .article-content
=> Added a small margin bottom to improve reading

public/css/style.css
Added max-width: 1600px to fluid container to avoid too long reading lines on large display
=> Updated styles.css

app/views/templates/base.volt, app/views/templates/index.volt
Disabled Pingdom as discussed in the internal chat
=> Disabled Pingdom

app/views/error/show404.volt, app/views/error/show500.volt, boxfile.yml
=> Correct error views

app/providers/Logger/ServiceProvider.php, storage/setup/logrotate.d/.editorconfig, storage/setup/logrotate.d/phalcon-docs, storage/setup/nginx.conf
This allows us use proper log rotate tools e.g [`logrotate(8)`](https://linux.die.net/man/8/logrotate).
=> Do not use date in the log file name

_sass/_style.scss
=> remove unnecessary margin

_includes/language-selector-mobile.html, _includes/language-selector.html
Small SEO optimalisation for the docs.
=> Added SEO language indicator for links

_includes/footer-js.html, _sass/_codeblock.scss, assets/js/codeblock.js
Fixed styling copy to clipboard
=> Fixed styling copy to clipboard 

_sass/_style.scss
=> contact us container mobile & tablet fix

_sass/_style.scss
=> mobile footer upd

assets/css/style.css
Changed font color for numbers issue #202
=> Changed font color for numbers #202

3.4/uk-ua/sponsors.md
=> add sponsors table

3.4/en/environments-docker.md, 3.4/es-es/environments-docker.md
=> fix markdown

assets/css/custom.css, assets/js/main.js, assets/js/main.min.js
=> Make titles clicklable #210

_includes/head.html
Added full page to alternate url to fix google webmaster errors
=> Added full page to alternate url to fix google webmaster errors

_includes/head.html
=> Remove image/png type from favicon.ico file

_data/4-0-cs-cz-meta-topics.json, _data/4-0-de-de-meta-topics.json, _data/4-0-el-gr-meta-topics.json, _data/4-0-en-meta-topics.json, _data/4-0-es-es-meta-topics.json, _data/4-0-fa-ir-meta-topics.json, _data/4-0-fr-fr-meta-topics.json, _data/4-0-id-id-meta-topics.json, _data/4-0-it-it-meta-topics.json, _data/4-0-ja-jp-meta-topics.json, _data/4-0-nl-nl-meta-topics.json, _data/4-0-pl-pl-meta-topics.json, _data/4-0-pt-br-meta-topics.json, _data/4-0-ru-ru-meta-topics.json, _data/4-0-sr-sp-meta-topics.json, _data/4-0-th-th-meta-topics.json, _data/4-0-tr-tr-meta-topics.json, _data/4-0-uk-ua-meta-topics.json, _data/4-0-zh-cn-meta-topics.json
Corrected url to our 4.0 Changelog
=> Redirect users to correct url

_config.yml, _redirects
=> Set 4.0 as default

_includes/head.html
=> meta update

Gemfile
https://github.com/phalcon/docs-app/issues/247
=> docs update

3.4/cs-cz/acl.md, 3.4/de-de/acl.md, 3.4/en/acl.md, 3.4/es-es/acl.md, 3.4/fa-ir/acl.md, 3.4/fr-fr/acl.md, 3.4/id-id/acl.md, 3.4/it-it/acl.md, 3.4/ja-jp/acl.md, 3.4/pl-pl/acl.md, 3.4/ru-ru/acl.md, 3.4/tr-tr/acl.md, 3.4/uk-ua/acl.md, 3.4/zh-cn/acl.md
https://github.com/phalcon/docs-app/issues/282
=> update acl.md links

3.4/cs-cz/api/Phalcon_Annotations.md, 3.4/de-de/api/Phalcon_Annotations.md, 3.4/en/api/Phalcon_Annotations.md, 3.4/es-es/api/Phalcon_Annotations.md, 3.4/fa-ir/api/Phalcon_Annotations.md, 3.4/fr-fr/api/Phalcon_Annotations.md, 3.4/id-id/api/Phalcon_Annotations.md, 3.4/it-it/api/Phalcon_Annotations.md, 3.4/ja-jp/api/Phalcon_Annotations.md, 3.4/pl-pl/api/Phalcon_Annotations.md, 3.4/ru-ru/api/Phalcon_Annotations.md, 3.4/tr-tr/api/Phalcon_Annotations.md, 3.4/uk-ua/api/Phalcon_Annotations.md, 3.4/ur-in/api/Phalcon_Annotations.md, 3.4/zh-cn/api/Phalcon_Annotations.md
https://github.com/phalcon/docs-app/issues/284
=> update Phalcon_Annotations.md links

assets/css/custom.css
resolve https://github.com/phalcon/docs-app/issues/371
=> fix search bar

3.4/cs-cz/contributions.md, 3.4/de-de/contributions.md, 3.4/en/contributions.md, 3.4/es-es/contributions.md, 3.4/fa-ir/contributions.md, 3.4/fr-fr/contributions.md, 3.4/id-id/contributions.md, 3.4/it-it/contributions.md, 3.4/ja-jp/contributions.md, 3.4/pl-pl/contributions.md, 3.4/ru-ru/contributions.md, 3.4/uk-ua/contributions.md, 3.4/ur-in/contributions.md, 3.4/zh-cn/contributions.md
resolve https://github.com/phalcon/docs-app/issues/373
=> update contributions links

3.4/cs-cz/cookies.md, 3.4/de-de/cookies.md, 3.4/en/cookies.md, 3.4/es-es/cookies.md
resolve https://github.com/phalcon/docs-app/issues/375
=> update cookies.md links

3.4/cs-cz/crypt.md, 3.4/de-de/crypt.md, 3.4/en/crypt.md, 3.4/es-es/crypt.md, 3.4/fa-ir/crypt.md, 3.4/fr-fr/crypt.md, 3.4/id-id/crypt.md, 3.4/it-it/crypt.md, 3.4/ja-jp/crypt.md, 3.4/pl-pl/crypt.md, 3.4/ru-ru/crypt.md, 3.4/tr-tr/crypt.md, 3.4/uk-ua/crypt.md, 3.4/ur-in/crypt.md, 3.4/zh-cn/crypt.md
resolve https://github.com/phalcon/docs-app/issues/377
=> update crypt.md links

3.4/cs-cz/db-layer.md, 3.4/de-de/db-layer.md, 3.4/en/db-layer.md, 3.4/es-es/db-layer.md, 3.4/fa-ir/db-layer.md, 3.4/fr-fr/db-layer.md, 3.4/id-id/db-layer.md, 3.4/it-it/db-layer.md, 3.4/ja-jp/db-layer.md, 3.4/pl-pl/db-layer.md, 3.4/ru-ru/db-layer.md, 3.4/tr-tr/db-layer.md, 3.4/uk-ua/db-layer.md, 3.4/ur-in/db-layer.md, 3.4/zh-cn/db-layer.md
resolve https://github.com/phalcon/docs-app/issues/379
=> update db-layer.md links

3.4/de-de/db-odm.md, 3.4/en/db-odm.md, 3.4/es-es/db-odm.md, 3.4/fa-ir/db-odm.md, 3.4/fr-fr/db-odm.md, 3.4/id-id/db-odm.md, 3.4/ja-jp/db-odm.md, 3.4/pl-pl/db-odm.md, 3.4/ru-ru/db-odm.md, 3.4/tr-tr/db-odm.md, 3.4/uk-ua/db-odm.md, 3.4/ur-in/db-odm.md, 3.4/zh-cn/db-odm.md
resolve https://github.com/phalcon/docs-app/issues/389
=> update db-odm.md links

3.4/cs-cz/devtools-usage.md, 3.4/de-de/devtools-usage.md, 3.4/es-es/devtools-usage.md, 3.4/it-it/devtools-usage.md, 3.4/pl-pl/devtools-usage.md, 3.4/tr-tr/devtools-usage.md, 3.4/uk-ua/devtools-usage.md, 3.4/ur-in/devtools-usage.md, 3.4/zh-cn/devtools-usage.md
resolve https://github.com/phalcon/docs-app/issues/398
=> update devtools-usage.md link

3.4/cs-cz/di.md, 3.4/de-de/di.md, 3.4/es-es/di.md, 3.4/fa-ir/di.md, 3.4/fr-fr/di.md, 3.4/id-id/di.md, 3.4/it-it/di.md, 3.4/ja-jp/di.md, 3.4/pl-pl/di.md, 3.4/ru-ru/di.md, 3.4/tr-tr/di.md, 3.4/uk-ua/di.md, 3.4/ur-in/di.md, 3.4/zh-cn/di.md
resolve https://github.com/phalcon/docs-app/issues/400
=> update di.md link

3.4/cs-cz/escaper.md, 3.4/de-de/escaper.md, 3.4/en/escaper.md, 3.4/es-es/escaper.md, 3.4/fa-ir/escaper.md, 3.4/fr-fr/escaper.md, 3.4/id-id/escaper.md, 3.4/it-it/escaper.md, 3.4/ja-jp/escaper.md, 3.4/pl-pl/escaper.md, 3.4/ru-ru/escaper.md, 3.4/tr-tr/escaper.md, 3.4/uk-ua/escaper.md, 3.4/ur-in/escaper.md, 3.4/zh-cn/escaper.md
resolve https://github.com/phalcon/docs-app/issues/404
=> update escaper.md links

3.4/cs-cz/generating-backtrace.md, 3.4/de-de/generating-backtrace.md, 3.4/en/generating-backtrace.md, 3.4/es-es/generating-backtrace.md, 3.4/fa-ir/generating-backtrace.md, 3.4/fr-fr/generating-backtrace.md, 3.4/id-id/generating-backtrace.md, 3.4/it-it/generating-backtrace.md, 3.4/ja-jp/generating-backtrace.md, 3.4/pl-pl/generating-backtrace.md, 3.4/ru-ru/generating-backtrace.md, 3.4/tr-tr/generating-backtrace.md, 3.4/uk-ua/generating-backtrace.md, 3.4/ur-in/generating-backtrace.md, 3.4/zh-cn/generating-backtrace.md
resolve https://github.com/phalcon/docs-app/issues/406
=> update generating-backtrace.md links

3.4/cs-cz/i18n.md, 3.4/de-de/i18n.md, 3.4/en/i18n.md, 3.4/es-es/i18n.md, 3.4/fa-ir/i18n.md, 3.4/fr-fr/i18n.md, 3.4/id-id/i18n.md, 3.4/it-it/i18n.md, 3.4/ja-jp/i18n.md, 3.4/pl-pl/i18n.md, 3.4/ru-ru/i18n.md, 3.4/tr-tr/i18n.md, 3.4/uk-ua/i18n.md, 3.4/ur-in/i18n.md, 3.4/zh-cn/i18n.md
resolve https://github.com/phalcon/docs-app/issues/408
=> update i18n.md links

3.4/cs-cz/image.md, 3.4/de-de/image.md, 3.4/en/image.md, 3.4/es-es/image.md, 3.4/fa-ir/image.md, 3.4/fr-fr/image.md, 3.4/id-id/image.md, 3.4/it-it/image.md, 3.4/ja-jp/image.md, 3.4/pl-pl/image.md, 3.4/ru-ru/image.md, 3.4/uk-ua/image.md, 3.4/ur-in/image.md, 3.4/zh-cn/image.md
resolve https://github.com/phalcon/docs-app/issues/410
=> update image.md links

3.4/cs-cz/installation.md, 3.4/de-de/installation.md, 3.4/en/installation.md, 3.4/es-es/installation.md, 3.4/fa-ir/installation.md, 3.4/fr-fr/installation.md, 3.4/id-id/installation.md, 3.4/it-it/installation.md, 3.4/ja-jp/installation.md, 3.4/pl-pl/installation.md, 3.4/ru-ru/installation.md, 3.4/tr-tr/installation.md, 3.4/uk-ua/installation.md, 3.4/ur-in/installation.md, 3.4/zh-cn/installation.md
resolve https://github.com/phalcon/docs-app/issues/412
=> update installation.md links

3.4/cs-cz/loader.md, 3.4/de-de/loader.md, 3.4/en/loader.md, 3.4/es-es/loader.md, 3.4/fa-ir/loader.md, 3.4/fr-fr/loader.md, 3.4/id-id/loader.md, 3.4/it-it/loader.md, 3.4/ja-jp/loader.md, 3.4/pl-pl/loader.md, 3.4/ru-ru/loader.md, 3.4/tr-tr/loader.md, 3.4/uk-ua/loader.md, 3.4/ur-in/loader.md, 3.4/zh-cn/loader.md
resolve https://github.com/phalcon/docs-app/issues/414
=> update loader.md links

3.4/cs-cz/logging.md, 3.4/de-de/logging.md, 3.4/en/logging.md, 3.4/es-es/logging.md, 3.4/fa-ir/logging.md, 3.4/fr-fr/logging.md, 3.4/id-id/logging.md, 3.4/it-it/logging.md, 3.4/ja-jp/logging.md, 3.4/pl-pl/logging.md, 3.4/ru-ru/logging.md, 3.4/tr-tr/logging.md, 3.4/uk-ua/logging.md, 3.4/ur-in/logging.md, 3.4/zh-cn/logging.md
resolve https://github.com/phalcon/docs-app/issues/416
=> update logging.md links

3.4/cs-cz/new-feature-request.md, 3.4/de-de/new-feature-request.md, 3.4/en/new-feature-request.md, 3.4/es-es/new-feature-request.md, 3.4/fa-ir/new-feature-request.md, 3.4/fr-fr/new-feature-request.md, 3.4/id-id/new-feature-request.md, 3.4/it-it/new-feature-request.md, 3.4/ja-jp/new-feature-request.md, 3.4/pl-pl/new-feature-request.md, 3.4/ru-ru/new-feature-request.md, 3.4/tr-tr/new-feature-request.md, 3.4/uk-ua/new-feature-request.md, 3.4/ur-in/new-feature-request.md, 3.4/zh-cn/new-feature-request.md
resolve https://github.com/phalcon/docs-app/issues/420
=> update new-feature-request.md links

3.4/cs-cz/queue.md, 3.4/de-de/queue.md, 3.4/en/queue.md, 3.4/es-es/queue.md, 3.4/fa-ir/queue.md, 3.4/fr-fr/queue.md, 3.4/id-id/queue.md, 3.4/it-it/queue.md, 3.4/ja-jp/queue.md, 3.4/pl-pl/queue.md, 3.4/ru-ru/queue.md, 3.4/tr-tr/queue.md, 3.4/uk-ua/queue.md, 3.4/ur-in/queue.md, 3.4/zh-cn/queue.md
resolve https://github.com/phalcon/docs-app/issues/422
=> update queue.md links

3.4/cs-cz/request.md, 3.4/de-de/request.md, 3.4/en/request.md, 3.4/es-es/request.md, 3.4/fa-ir/request.md, 3.4/fr-fr/request.md, 3.4/id-id/request.md, 3.4/it-it/request.md, 3.4/ja-jp/request.md, 3.4/pl-pl/request.md, 3.4/ru-ru/request.md, 3.4/tr-tr/request.md, 3.4/uk-ua/request.md, 3.4/ur-in/request.md, 3.4/zh-cn/request.md
resolve https://github.com/phalcon/docs-app/issues/424
=> update request.md links

3.4/cs-cz/routing.md, 3.4/de-de/routing.md, 3.4/en/routing.md, 3.4/es-es/routing.md, 3.4/fa-ir/routing.md, 3.4/fr-fr/routing.md, 3.4/id-id/routing.md, 3.4/it-it/routing.md, 3.4/ja-jp/routing.md, 3.4/pl-pl/routing.md, 3.4/ru-ru/routing.md, 3.4/tr-tr/routing.md, 3.4/uk-ua/routing.md, 3.4/ur-in/routing.md, 3.4/zh-cn/routing.md
resolve https://github.com/phalcon/docs-app/issues/426
=> update routing.md links

3.4/cs-cz/security.md, 3.4/de-de/security.md, 3.4/en/security.md, 3.4/es-es/security.md, 3.4/fa-ir/security.md, 3.4/fr-fr/security.md, 3.4/id-id/security.md, 3.4/it-it/security.md, 3.4/ja-jp/security.md, 3.4/pl-pl/security.md, 3.4/ru-ru/security.md, 3.4/tr-tr/security.md, 3.4/uk-ua/security.md, 3.4/ur-in/security.md, 3.4/zh-cn/security.md
resolve https://github.com/phalcon/docs-app/issues/428
=> update security.md links

3.4/cs-cz/translate.md, 3.4/de-de/translate.md, 3.4/en/translate.md, 3.4/es-es/translate.md, 3.4/fa-ir/translate.md, 3.4/fr-fr/translate.md, 3.4/id-id/translate.md, 3.4/it-it/translate.md, 3.4/ja-jp/translate.md, 3.4/pl-pl/translate.md, 3.4/ru-ru/translate.md, 3.4/tr-tr/translate.md, 3.4/uk-ua/translate.md, 3.4/ur-in/translate.md, 3.4/zh-cn/translate.md
resolve https://github.com/phalcon/docs-app/issues/432
=> update translate.md links

3.4/cs-cz/tutorial-basic.md, 3.4/de-de/tutorial-basic.md, 3.4/en/tutorial-basic.md, 3.4/es-es/tutorial-basic.md, 3.4/fa-ir/tutorial-basic.md, 3.4/fr-fr/tutorial-basic.md, 3.4/id-id/tutorial-basic.md, 3.4/it-it/tutorial-basic.md, 3.4/ja-jp/tutorial-basic.md, 3.4/ru-ru/tutorial-basic.md, 3.4/tr-tr/tutorial-basic.md, 3.4/uk-ua/tutorial-basic.md, 3.4/ur-in/tutorial-basic.md, 3.4/zh-cn/tutorial-basic.md
resolve https://github.com/phalcon/docs-app/issues/434
=> update tutorial-basic.md link

3.4/cs-cz/tutorial-invo.md, 3.4/de-de/tutorial-invo.md, 3.4/en/tutorial-invo.md, 3.4/es-es/tutorial-invo.md, 3.4/fa-ir/tutorial-invo.md, 3.4/fr-fr/tutorial-invo.md, 3.4/id-id/tutorial-invo.md, 3.4/it-it/tutorial-invo.md, 3.4/ja-jp/tutorial-invo.md, 3.4/pl-pl/tutorial-invo.md, 3.4/ru-ru/tutorial-invo.md, 3.4/tr-tr/tutorial-invo.md, 3.4/uk-ua/tutorial-invo.md, 3.4/ur-in/tutorial-invo.md, 3.4/zh-cn/tutorial-invo.md
resolve https://github.com/phalcon/docs-app/issues/437
=> update tutorial-invo.md links

4.0/de-de/api/phalcon_crypt.md, 4.0/el-gr/api/phalcon_crypt.md, 4.0/en/api/phalcon_crypt.md, 4.0/es-es/api/phalcon_crypt.md, 4.0/fa-ir/api/phalcon_crypt.md, 4.0/fr-fr/api/phalcon_crypt.md, 4.0/id-id/api/phalcon_crypt.md, 4.0/it-it/api/phalcon_crypt.md, 4.0/ja-jp/api/phalcon_crypt.md, 4.0/ko-kr/api/phalcon_crypt.md, 4.0/pl-pl/api/phalcon_crypt.md, 4.0/pt-br/api/phalcon_crypt.md, 4.0/ru-ru/api/phalcon_crypt.md, 4.0/tr-tr/api/phalcon_crypt.md, 4.0/uk-ua/api/phalcon_crypt.md, 4.0/zh-cn/api/phalcon_crypt.md
resolve https://github.com/phalcon/docs-app/issues/449
=> update phalcon_crypt v4

4.0/cs-cz/api/phalcon_http.md, 4.0/de-de/api/phalcon_http.md, 4.0/el-gr/api/phalcon_http.md, 4.0/en/api/phalcon_http.md, 4.0/es-es/api/phalcon_http.md, 4.0/fa-ir/api/phalcon_http.md, 4.0/fr-fr/api/phalcon_http.md, 4.0/id-id/api/phalcon_http.md, 4.0/it-it/api/phalcon_http.md, 4.0/ja-jp/api/phalcon_http.md, 4.0/ko-kr/api/phalcon_http.md, 4.0/pl-pl/api/phalcon_http.md, 4.0/pt-br/api/phalcon_http.md, 4.0/ru-ru/api/phalcon_http.md, 4.0/tr-tr/api/phalcon_http.md, 4.0/uk-ua/api/phalcon_http.md
resolve https://github.com/phalcon/docs-app/issues/451
=> update phalcon_http v4

4.0/cs-cz/api/phalcon_image.md, 4.0/de-de/api/phalcon_image.md, 4.0/el-gr/api/phalcon_image.md, 4.0/en/api/phalcon_image.md, 4.0/es-es/api/phalcon_image.md, 4.0/fa-ir/api/phalcon_image.md, 4.0/fr-fr/api/phalcon_image.md, 4.0/id-id/api/phalcon_image.md, 4.0/it-it/api/phalcon_image.md, 4.0/ja-jp/api/phalcon_image.md, 4.0/ko-kr/api/phalcon_image.md, 4.0/pl-pl/api/phalcon_image.md, 4.0/pt-br/api/phalcon_image.md, 4.0/ru-ru/api/phalcon_image.md, 4.0/tr-tr/api/phalcon_image.md, 4.0/uk-ua/api/phalcon_image.md, 4.0/zh-cn/api/phalcon_image.md
resolve https://github.com/phalcon/docs-app/issues/453
=> update phalcon_image v4

4.0/cs-cz/api/phalcon_logger.md, 4.0/de-de/api/phalcon_logger.md, 4.0/el-gr/api/phalcon_logger.md, 4.0/en/api/phalcon_logger.md, 4.0/es-es/api/phalcon_logger.md, 4.0/fa-ir/api/phalcon_logger.md, 4.0/fr-fr/api/phalcon_logger.md, 4.0/id-id/api/phalcon_logger.md, 4.0/it-it/api/phalcon_logger.md, 4.0/ja-jp/api/phalcon_logger.md, 4.0/ko-kr/api/phalcon_logger.md, 4.0/pl-pl/api/phalcon_logger.md, 4.0/pt-br/api/phalcon_logger.md, 4.0/ru-ru/api/phalcon_logger.md, 4.0/tr-tr/api/phalcon_logger.md, 4.0/uk-ua/api/phalcon_logger.md, 4.0/zh-cn/api/phalcon_logger.md
resolve https://github.com/phalcon/docs-app/issues/455
=> update phalcon_logger v4

4.0/cs-cz/api/phalcon_security.md, 4.0/de-de/api/phalcon_security.md, 4.0/el-gr/api/phalcon_security.md, 4.0/en/api/phalcon_security.md, 4.0/es-es/api/phalcon_security.md, 4.0/fa-ir/api/phalcon_security.md, 4.0/fr-fr/api/phalcon_security.md, 4.0/id-id/api/phalcon_security.md, 4.0/it-it/api/phalcon_security.md, 4.0/ja-jp/api/phalcon_security.md, 4.0/ko-kr/api/phalcon_security.md, 4.0/pl-pl/api/phalcon_security.md, 4.0/pt-br/api/phalcon_security.md, 4.0/ru-ru/api/phalcon_security.md, 4.0/tr-tr/api/phalcon_security.md, 4.0/uk-ua/api/phalcon_security.md, 4.0/zh-cn/api/phalcon_security.md
resolve https://github.com/phalcon/docs-app/issues/457
=> update phalcon_security v4

4.0/cs-cz/contributions.md, 4.0/de-de/contributions.md, 4.0/el-gr/contributions.md, 4.0/en/contributions.md, 4.0/es-es/contributions.md, 4.0/fa-ir/contributions.md, 4.0/fr-fr/contributions.md, 4.0/id-id/contributions.md, 4.0/it-it/contributions.md, 4.0/ja-jp/contributions.md, 4.0/ko-kr/contributions.md, 4.0/pl-pl/contributions.md, 4.0/pt-br/contributions.md, 4.0/ru-ru/contributions.md, 4.0/tr-tr/contributions.md, 4.0/uk-ua/contributions.md, 4.0/zh-cn/contributions.md
resolve https://github.com/phalcon/docs-app/issues/459
=> update contributions v4
